# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
# ------------- #
#  main config  #
# ------------- #
title: zcr's blog
email: 274153451@qq.com
description: >- # this means to ignore newlines until "baseurl:"
  暂无
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://s2405330.github.io" # the base hostname & protocol for your site, e.g. http://example.com
date_format: "ordinal"
keywords: blog,Android
timezone: Asia/Shanghai
encoding: "utf-8"
side_bar_repo_limit: 5

# ---------------- #
#      Author      #
# ---------------- #
author: Zhou Chao Ran
organization: null
organization_url: null
github_username: s2405330
location: ShenZhen, China
email: s2405330@163.com

# ---------------- #
#    Navigation    #
# ---------------- #
navs:
  -
    href: /
    label: 首页

  -
    href: /categories/
    label: 分类

  -
    href: /links/
    label: 链接

  -
    href: /about/
    label: 关于

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

repository: s2405330/s2405330.github.io

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
